api-version: 2024-02-02-preview
location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    runtime:
      dotnet:
        autoConfigureDataProtection: true
    ingress:
      additionalPortMappings:
        - targetPort: 9000
          external: false
      external: false
      targetPort: 8080
      transport: http
      allowInsecure: true
    registries:
      - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
        identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
    secrets:
      - name: kc-bootstrap-admin-password
        value: '{{ securedParameter "keycloak_password" }}'
  template:
    containers:
      - image: {{ .Image }}
        name: keycloak
        args:
          - start
          - --import-realm
        env:
          - name: AZURE_CLIENT_ID
            value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
          - name: KC_BOOTSTRAP_ADMIN_USERNAME
            value: admin
          - name: KC_HEALTH_ENABLED
            value: "true"
          - name: KC_BOOTSTRAP_ADMIN_PASSWORD
            secretRef: kc-bootstrap-admin-password
    scale:
      minReplicas: 0
      maxReplicas: 2
tags:
  azd-service-name: keycloak
  aspire-resource-name: keycloak
